"""
Chapter 6: Programmatic Tool Caller.

Implements the client-side orchestration logic for Anthropic's
Programmatic Tool Calling (PTC) feature. Manages code execution simulation,
tool call extraction from orchestration code, and result processing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple


@dataclass
class CodeExecutionResult:
    """Encapsulates the result of code execution.

    Corresponds to the ``code_execution_tool_result`` content block
    in the Anthropic Messages API response.
    """

    stdout: str = ""
    stderr: str = ""
    return_code: int = 0
    container_id: Optional[str] = None
    expires_at: Optional[str] = None


@dataclass
class ProgrammaticToolCall:
    """Represents a tool call made from within code execution.

    Distinguished from direct tool calls by the ``caller`` field in
    the API response: ``{"type": "code_execution_20260120", "tool_id": "..."}``.
    """

    tool_name: str
    input_data: Dict[str, Any] = field(default_factory=dict)
    caller_tool_id: str = ""
    tool_use_id: str = ""


class ProgrammaticToolCaller:
    """Manages programmatic tool calling orchestration.

    In production, Anthropic's Code Execution environment runs Claude's
    Python code in a sandbox. This class simulates the client-side
    orchestration logic: parsing tool calls from code, managing pending
    calls, and formatting results.

    Usage::

        caller = ProgrammaticToolCaller()
        result = caller.execute_code('''
            data = query_database("SELECT * FROM orders")
            summary = filter_and_aggregate(data)
            print(json.dumps(summary))
        ''')
        print(caller.pending_calls)  # Inspect extracted tool calls
    """

    def __init__(self) -> None:
        self._container_id: Optional[str] = None
        self._pending_calls: List[ProgrammaticToolCall] = []

    # ------------------------------------------------------------------
    # Code execution simulation
    # ------------------------------------------------------------------

    def execute_code(self, code: str) -> CodeExecutionResult:
        """Parse orchestration code and extract tool calls.

        In a real PTC workflow, Claude's generated code runs in a
        sandboxed Python environment. This method simulates the
        extraction step: it parses the code to identify which tools
        are being called and records them as pending calls.

        Args:
            code: Python orchestration code generated by Claude.

        Returns:
            CodeExecutionResult with stdout/stderr reflecting parse results.
        """
        # Clear any previous pending state
        self._pending_calls.clear()

        tool_calls = self.extract_tool_calls(code)

        if not tool_calls:
            return CodeExecutionResult(
                stdout="",
                stderr="No tool calls found in code",
                return_code=0,
            )

        self._pending_calls = tool_calls

        return CodeExecutionResult(
            stdout="",
            stderr="",
            return_code=0,
        )

    def extract_tool_calls(self, code: str) -> List[ProgrammaticToolCall]:
        """Extract function call patterns from orchestration code.

        Matches patterns like:
        - ``result = await tool_name(...)``
        - ``tool_name(...)``
        - ``data = tool_name(key="value")``

        Args:
            code: Python source code.

        Returns:
            List of ProgrammaticToolCall records in order of appearance.
        """
        import re

        calls: List[ProgrammaticToolCall] = []

        # Pattern: optional "await", function name, opening paren, args, closing paren
        pattern = r"(?:await\s+)?(\w+)\s*\(([^)]*)\)"
        for match in re.finditer(pattern, code):
            func_name = match.group(1)
            args_str = match.group(2)

            parsed_input = self._parse_arguments(args_str)

            call = ProgrammaticToolCall(
                tool_name=func_name,
                input_data=parsed_input,
                caller_tool_id="",
                tool_use_id=f"toolu_{len(calls):04d}",
            )
            calls.append(call)

        return calls

    def _parse_arguments(self, args_str: str) -> Dict[str, Any]:
        """Parse function call arguments into a dictionary.

        Handles simple cases:
        - ``'engineering'`` → positional
        - ``key='value'`` → keyword
        - ``key=123`` → keyword integer

        For full argument parsing, an AST-based approach is recommended.
        """
        import json

        args_str = args_str.strip()
        result: Dict[str, Any] = {}

        if not args_str:
            return result

        # Check for keyword args: ``key=value`` patterns
        kwarg_pattern = r"""(\w+)\s*=\s*(?:
            '(?:[^'\\]|\\.)*'
            |
            "(?:[^"\\]|\\.)*"
            |
            \d+(?:\.\d+)?
            |
            True|False|None
            |
            \w+
        )"""
        import re

        has_kwargs = False
        for m in re.finditer(kwarg_pattern, args_str):
            has_kwargs = True
            key = m.group(1)
            val = m.group(0).split("=", 1)[1].strip()
            # Strip quotes
            if (val.startswith("'") and val.endswith("'")) or (
                val.startswith('"') and val.endswith('"')
            ):
                val = val[1:-1]
            elif val.isdigit():
                val = int(val)
            elif val == "True":
                val = True
            elif val == "False":
                val = False
            elif val == "None":
                val = None
            result[key] = val

        if not has_kwargs:
            # Positional args
            result["_args"] = [
                a.strip().strip("'").strip('"') for a in args_str.split(",")
            ]

        return result

    # ------------------------------------------------------------------
    # Result processing
    # ------------------------------------------------------------------

    def process_tool_results(
        self, results: List[Dict[str, Any]]
    ) -> str:
        """Process tool execution results into final output.

        Simulates what ``print(json.dumps(...))`` would produce after
        all tool calls have completed in the code execution environment.

        Args:
            results: List of ``{"tool_name": "...", "result": ...}``.

        Returns:
            Newline-separated JSON strings representing the final stdout.
        """
        import json

        lines = []
        for result in results:
            lines.append(
                json.dumps(result, ensure_ascii=False, default=str)
            )
        return "\n".join(lines)

    def format_tool_result_for_api(
        self, tool_use_id: str, result_content: str
    ) -> Dict[str, Any]:
        """Create a properly formatted ``tool_result`` content block.

        Args:
            tool_use_id: The ``id`` from the ``tool_use`` block.
            result_content: The result string to return.

        Returns:
            A dict ready for inclusion in the ``user`` message content array.
        """
        return {
            "type": "tool_result",
            "tool_use_id": tool_use_id,
            "content": result_content,
        }

    # ------------------------------------------------------------------
    # Container management
    # ------------------------------------------------------------------

    @property
    def container_id(self) -> Optional[str]:
        """Current container ID for code execution continuity."""
        return self._container_id

    def set_container(self, container_id: str) -> None:
        """Set the container ID for subsequent requests.

        Reusing containers preserves state across multiple code
        execution sessions.
        """
        self._container_id = container_id

    def reset_container(self) -> None:
        """Clear container state and pending calls."""
        self._container_id = None
        self._pending_calls.clear()

    @property
    def pending_calls(self) -> List[ProgrammaticToolCall]:
        """Currently pending tool calls waiting for execution."""
        return list(self._pending_calls)

    @property
    def has_pending_calls(self) -> bool:
        """Whether there are unprocessed tool calls."""
        return len(self._pending_calls) > 0
